### ISSUE TITLE
ggtrendline is GREAT + quick Question

### ISSUE THREAD

**Issue by sfd99** [PhDMeiwp/ggtrendline#3]
**_Hi Weiping,_**

Really like the ggtrendline PKG.
Easy to use 
and very helpful !.

The **EQ text line** 
and the **R2 text line** are by default very small 
and _hard to read_.

I was able to make 
the text font _bigger,_,
using the **eSize** parameter = 5.

**Q:**
How to _position_ 
**the EQ text line** 
and **the R2 text line** more to the center of the plot?.

Right now,
these 2 important text lines are almost "cut-off"
on the left side of the plot...

I'd like to move them horizontally,
a _little to the right of the plot_. ===>

Here's my test code,
with the larger font...**eSize=5**

```
 x <- iris$Petal.Width
 y <- iris$Petal.Length
 group <- iris$Species
 ggtrendline(x,y,"exp3P",   eSize=5  )  + geom_point(aes(x,y,color=group))

````
Help, Weiping!

**SFd99
San Francisco
ggtrendline PKG v 1.0.3
latest version of R, RStudio and Ubuntu LINUX 20.04.**

**Comment by PhDMeiwp** [comment]
Hi, [sfd99](https://github.com/sfd99)

Thanks for your comments. In the ggtrendline package, 

- the arguments  'eq.x' and 'eq.y' are for the equation position, 

- and the arguments 'rrp.x' and 'rrp.y' are for the R^2 and P-vlaue position.

Try the following codes:
```
library(ggplot2)
library(ggtrendline)
x <- iris$Petal.Width
 y <- iris$Petal.Length
 group <- iris$Species
 ggtrendline(x, y, "exp3P", eSize = 5, eq.x = 1, eq.y = 6.5, rrp.x = 1, rrp.y = 5.8)  + 
                     geom_point(aes(x, y, color = group))
```

Best regards
![position](https://user-images.githubusercontent.com/26179142/167984024-6d38c82c-1562-4951-a4cb-6902a6ac2baa.png)

**Comment by sfd99** [comment]
_Perfect, Weiping!._

I guess my [Plot Panel] in Rstudio
was  sized too small, 
so the **EQ** and **R2** lines were "cut-off"
and I was losing some of that text...

Works great now!.

Thank you / 谢谢你 

**PS:** 

in addition to params:
**xlab** and **ylab** ,
would also be nice to add 
a **label parameter**  (**_glab_** ?)
for the "group" LEGEND label,
(shown on the right of the plot).

So you could add :
 **glab="Species"** 
for the iris example :-)
 

**SFd99
San Francisco
ggtrendline PKG v 1.0.3
latest version of R, RStudio and Ubuntu LINUX 20.04.**

**Comment by PhDMeiwp** [comment]
Thank you.

The legend title could be modified as follows:

```
library(ggtrendline)
library(ggplot2)
x <- iris$Petal.Width
y <- iris$Petal.Length
group <- iris$Species
```

# Option1: use labs()
```
ggtrendline(x, y, "exp3P", eSize = 5, eq.x = 1, eq.y = 6.5, rrp.x = 1, rrp.y = 5.8)  + 
    geom_point(aes(x, y, color = group))+
    labs(color = "DIY legend")
```

# Option 2: use guides()
```
ggtrendline(x, y, "exp3P", eSize = 5, eq.x = 1, eq.y = 6.5, rrp.x = 1, rrp.y = 5.8)  + 
    geom_point(aes(x, y, color = group))+
    guides(color = guide_legend(title = "DIY2"))
```

# Option 3: directly change the group name, i.e., Species <-  iris$Species
```
library(ggtrendline)
library(ggplot2)
x <- iris$Petal.Width
y <- iris$Petal.Length
Species <- iris$Species
ggtrendline(x, y, "exp3P", eSize = 5, eq.x = 1, eq.y = 6.5, rrp.x = 1, rrp.y = 5.8)  + 
    geom_point(aes(x, y, color = Species))
```

# Option 4: change x- ,y-axis labels and legend label.
```
library(ggtrendline)
library(ggplot2)
x <- iris$Petal.Width
y <- iris$Petal.Length
group <- iris$Species

ggtrendline(x, y, "exp3P", eSize = 5, eq.x = 1, eq.y = 6.5, rrp.x = 1, rrp.y = 5.8,
                    xlab = "DIY xname", ylab = "DIY yname")  + 
    geom_point(aes(x, y, color = group))+
    labs(color = "DIY legend")
```

Best regards

![DIY](https://user-images.githubusercontent.com/26179142/167988791-360f9658-bed4-4a67-951f-48e568dcda39.png)

**Comment by sfd99** [comment]
Ah, understood.
Thank you, Weiping.

**ggtrendline** PKG
is _truly_ very good.


**SFd99
San Francisco
ggtrendline PKG v 1.0.3
latest version of R, RStudio and Ubuntu LINUX 20.04.**
